"""added url_id , qa_id in embedding tables

Revision ID: 4214f3e2567f
Revises: 5d4ba9ea79ff
Create Date: 2026-02-05 07:17:20.238332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4214f3e2567f'
down_revision: Union[str, Sequence[str], None] = '5d4ba9ea79ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_embeddings', sa.Column('url_id', sa.BigInteger(), nullable=True))
    op.add_column('file_embeddings', sa.Column('qa_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_embeddings', 'qa_id')
    op.drop_column('file_embeddings', 'url_id')
    # ### end Alembic commands ###
