"""added column for tokens

Revision ID: aa6137ad68b7
Revises: 4214f3e2567f
Create Date: 2026-02-05 10:18:09.611455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6137ad68b7'
down_revision: Union[str, Sequence[str], None] = '4214f3e2567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('file_embeddings', sa.Column('embedding_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_embeddings', 'embedding_tokens')
    op.drop_column('chats', 'total_tokens')
    op.drop_column('chats', 'completion_tokens')
    op.drop_column('chats', 'prompt_tokens')
    # ### end Alembic commands ###
