"""added source url column

Revision ID: efdc2b94ceb9
Revises: aa6137ad68b7
Create Date: 2026-02-11 09:57:21.191726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdc2b94ceb9'
down_revision: Union[str, Sequence[str], None] = 'aa6137ad68b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_embeddings', sa.Column('source_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_embeddings', 'source_url')
    # ### end Alembic commands ###
